version: '2'

services:
  customerexampleapi:
    image: username/customerexampleapi:Debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
